services:
  - type: web
    runtime: static
    name: paulvante
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: "20"
